name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: kamal deploy
        run: bin/kamal deploy
        env:
          KAMAL_SERVER_IP: "${{ secrets.KAMAL_SERVER_IP }}"
          DOCKER_HUB_USERNAME: "${{ secrets.DOCKER_HUB_USERNAME }}"
          KAMAL_REGISTRY_PASSWORD: "${{ secrets.KAMAL_REGISTRY_PASSWORD }}"
