name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Verify secrets are set
        run: |
          if [[ -z "$KAMAL_SERVER_IP" ]]; then
            echo "❌ KAMAL_SERVER_IP secret is not set"
            exit 1
          fi
          if [[ -z "$DOCKER_HUB_USERNAME" ]]; then
            echo "❌ DOCKER_HUB_USERNAME secret is not set"  
            exit 1
          fi
          if [[ -z "$KAMAL_REGISTRY_PASSWORD" ]]; then
            echo "❌ KAMAL_REGISTRY_PASSWORD secret is not set"
            exit 1
          fi
          echo "✅ All required secrets are set"
        env:
          RAILS_ENV: production
          KAMAL_SERVER_IP: ${{ secrets.KAMAL_SERVER_IP }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      - name: kamal deploy
        run: bin/kamal deploy
        env:
          RAILS_ENV: production
          KAMAL_SERVER_IP: ${{ secrets.KAMAL_SERVER_IP }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
